export interface MethodOption {
  id: number;
  name: string;
}

export const METHODS: MethodOption[] = [
  { id: 1, name: "French Press" },
  { id: 2, name: "AeroPress" },
  { id: 3, name: "AeroPress Inverted" },
  { id: 4, name: "Delter" },
  { id: 5, name: "V60" },
  { id: 6, name: "Clever Dripper" },
  { id: 7, name: "LilyDrip" },
  { id: 8, name: "Immersion Switch" },
  { id: 9, name: "Origami" },
  { id: 10, name: "Koar" },
  { id: 11, name: "Kalita" },
  { id: 12, name: "Kalita Wave" },
  { id: 13, name: "Melitta" },
  { id: 14, name: "Kono" },
  { id: 15, name: "Daiso" },
  { id: 16, name: "Torch Mountain" },
  { id: 17, name: "April" },
  { id: 18, name: "Tricolate" },
  { id: 19, name: "VacOne" },
  { id: 20, name: "Fellow Stag" },
  { id: 21, name: "Phoenix" },
  { id: 22, name: "MiiR Pourigami" },
  { id: 23, name: "Gina" },
  { id: 24, name: "Chemex" },
  { id: 25, name: "Woodneck" },
  { id: 26, name: "Funnex" },
  { id: 27, name: "Moka" },
  { id: 28, name: "Espresso" },
  { id: 29, name: "Handpresso" },
  { id: 30, name: "Rok" },
  { id: 31, name: "Flair" },
  { id: 32, name: "Cafelat Robot" },
  { id: 33, name: "Leveroresso" },
  { id: 34, name: "Picopresso" },
  { id: 35, name: "Nanopresso" },
  { id: 36, name: "Minipresso" },
  { id: 37, name: "Pipamoka" },
  { id: 38, name: "Cuppamoka" },
  { id: 39, name: "Staresso Mini" },
  { id: 40, name: "Staresso" },
  { id: 41, name: "Staresso Pro" },
  { id: 42, name: "Trinity Zero" },
  { id: 43, name: "Trinity One" },
  { id: 44, name: "Cold Brew" },
  { id: 45, name: "Cold Aero" },
  { id: 46, name: "Cold Drip" },
  { id: 47, name: "Batch Brew" },
  { id: 48, name: "Syphon" },
  { id: 49, name: "Eva Solo" },
  { id: 50, name: "Cafflano Klassic" },
  { id: 51, name: "Cafflano Kompact" },
  { id: 52, name: "Cafflano Kompresso" },
  { id: 53, name: "Neapolitan Flip" },
  { id: 55, name: "Karisbader" },
  { id: 56, name: "Cezve" },
  { id: 57, name: "Orea" },
  { id: 58, name: "Drip Bag" },
  { id: 59, name: "Melodrip" },
  { id: 60, name: "Melodrip Colum" },
  { id: 61, name: "Phin" },
  { id: 62, name: "Pour Over" },
];
